import React from 'react'

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};


const About = () => {
  return (
    <div className='w-full min-h-screen flex items-center justify-center bg-gray-300'>
      <h1>About</h1>
    </div>
  )
}

export default About
