
import Footer from "./footer/page";
import "./globals.css";

import Navbar from './components/Navbar'



export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <Navbar/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
