
import React from 'react'
export const metadata = {
  title: "User Profile",
  description: "Generated by create next app",
};
const User = async({params}: {params: Promise<{id: string}>}) => {
    const {id}=await params
  return (
    <div>
      User {id}
    </div>
  )
}

export default User
