import React from 'react'

export const metadata = {
  title: "Footer",
  description: "Generated by create next app",
};

const Footer = () => {
  return (
    <div className='w-full flex flex-col items-center justify-center gap-4 py-6 bg-black text-white'>
      Footer
    </div>
  )
}

export default Footer
